#!/usr/bin/env php
<?php
/*
|-----------------------------------------------------------------------------
| Autor: Daniel da Costa e Faria
| Inspirado pelo artisan do Laravel
|-----------------------------------------------------------------------------
*/

use function core\pre;

define('appdir','apps');
define('sisdir','./');

//var_dump($argv);

require 'core/Functions.php';

require 'database/Connection.php';
/*
|-----------------------------------------------------------------------------
| Lista de argumentos
|-----------------------------------------------------------------------------
*/
$args  = $argv;
/*
|-----------------------------------------------------------------------------
| O segundo argumento é uma chamada para a função create
|-----------------------------------------------------------------------------
*/
if(isset($args[1]))
{
    $call = $args[1];
}else{
    echo "\e[1;37;41m Preciso saber o que quer fazer! \e[0m\n";
    echo "\e[1;37;41m Faça uma chamada assim: php genesis create, para ver exemplos! \e[0m\n";
    exit();
}

/*
|------------------------------------------------------
| Traduzindo o comando digitado pelo usuário
| Pegando o nome da funcao selecionada pelo usuario
|------------------------------------------------------
*/
$command = explode(':',$call);
$function = $command[0];

/*
|----------------------------------------------------------------------
| Depois de : deve ser informado o que será criado
| Pode ser uma aplicacao, um controller uma view, uma interface
|----------------------------------------------------------------------
*/
if(isset($command[1]))
{
    $type = $command[1];
}else{
    $type = '';
}

/*
|-------------------------------------------------------------------------
| O terceiro parametro é nome dado ao objeto criado
| Ex.: php genesis create:application loja
|-------------------------------------------------------------------------
*/
if(isset($args[2])){
    $name = $args[2];
}else{
    $name = NULL;
}

/*
|-------------------------------------------------------------------------------------
| Caso o usuario crie um model, pode apontar um banco de dados para gerar os
| models a partir do Class Builder. Pode se criar um Model apenas ou gerar todos os
| models. O banco deve estar configurado em apps/config/database.php
|-------------------------------------------------------------------------------------
*/
if(isset($args[3])){
    $database = $args[3];
}else{
    $database ='';
}

if(isset($args[4])){
    $params = $args[4];
}else{
    $params='myparams';
}
/*
|------------------------------------------------------------------------
| Faz a chamada da função 
| @param $function = nome da função
| @param $type = qual tipo de objeto será criado
| @param $name = qual o nome do objeto
| @param $database = nome do banco de dados
| @param $param = parametros adicionais
|------------------------------------------------------------------------
*/
call_user_func($function,$type,$name,$database,$params);
//Cria um arquivo de funcao na pasta core/make

function create($type, $name, $db='',$params='')
{
    if($type=='command')
    {
        $handle = fopen(sisdir.'/core/make/'.$name.'.php','w');
        $content  = "<?php \n";
        $name = str_replace('/','\\',$name);
        $classname = ucfirst($name);
        $content .= "class $classname{ \n\t";
        $content .= "public function do(\$name,\$db='',\$params=''){ \n\n\t";
        
        $content .= "}\n";             
        $content .= "}\n\t";
        fwrite($handle,$content);
        fclose($handle);
        echo "\e[0;32;12m Comando {$name} criado com sucesso!\e[0m\n";
    }else if ($type=='') {
        echo "\e[1;37;41m Comando create incompleto! \e[0m\n";
        echo "\e[1;37;41m Tente usar um destes comandos:
     
        create:application Cria uma nova aplicacao 
        create:controller  Cria um novo controller na pasta indicada 
        create:adminlte    Cria um painel de amdinistracao baseado no AdminLte
        create:view        Cria uma nova view na pasta indicada  
        create:model       Cria um model baseado na entidade indicada  
        create:modelform   Cria um formulario baseado na entidade indicada  
        create:form        Cria um formulario
        create:interface   Cria uma interface
        create:folder      Cria uma pasta 
    \e[0m\n";
    } else {
       make($type,$name,$db,$params);
    }
}//endcreate

function make($type,$name,$db,$params){
    require sisdir.'/core/AppMaker.php';
    $make = new AppMaker;
    $make->make($type,$name,$db,$params);
}